tex2png -lq '\prod' prod.png
tex2png -lq '\coprod' coprod.png
tex2png -lq '\oint' oint.png
tex2png -lq '\iint' iint.png
tex2png -lq '\iiint' iiint.png
tex2png -lq '\vdots' vdots.png
tex2png -lq '\cdots' cdots.png
tex2png -lq '\ddots' ddots.png
tex2png -lq '\hat{a}' hat{a}.png
tex2png -lq '\dot{a}' dot{a}.png
tex2png -lq '\bar{a}' bar{a}.png
tex2png -lq '\ddot{a}' ddot{a}.png
tex2png -lq '\overrightarrow{AB}' overrightarrow{AB}.png
tex2png -lq '\vec{a}' vec{a}.png
tex2png -lq '\overline{aaaa}' overline{aaaa}.png
tex2png -lq '\check{a}' check{a}.png
tex2png -lq '\tilde{a}' tilde{a}.png
tex2png -lq '\leq' leq.png
tex2png -lq '\geq' geq.png
tex2png -lq '\parallel' parallel.png
tex2png -lq '\nparallel' nparallel.png
tex2png -lq '\neq' neq.png
tex2png -lq '\approx' approx.png
tex2png -lq '\equiv' equiv.png
tex2png -lq '\doteq' doteq.png
tex2png -lq '\cong' cong.png
tex2png -lq '\simeq' simeq.png
tex2png -lq '\therefore' therefore.png
tex2png -lq '\because' because.png
tex2png -lq '\measuredangle' measuredangle.png
tex2png -lq '\sphericalangle' sphericalangle.png
tex2png -lq '\perp' perp.png
tex2png -lq '\pm' pm.png
tex2png -lq '\mp' mp.png
tex2png -lq '\div' div.png
tex2png -lq '\wedge' wedge.png
tex2png -lq '\vee' vee.png
tex2png -lq '\oplus' oplus.png
tex2png -lq '\ominus' ominus.png
tex2png -lq '\otimes' otimes.png
tex2png -lq '\odot' odot.png
tex2png -lq '\to' to.png
tex2png -lq '\gets' gets.png
tex2png -lq '\implies' implies.png
tex2png -lq '\leftrightarrow' leftrightarrow.png
tex2png -lq '\Leftrightarrow' Leftrightarrow.png
tex2png -lq '\iff' iff.png
tex2png -lq '\angle' angle.png
tex2png -lq '\in' in.png
tex2png -lq '\notin' notin.png
tex2png -lq '\ni' ni.png
tex2png -lq '\exists' exists.png
tex2png -lq '\subset' subset.png
tex2png -lq '\supset' supset.png
tex2png -lq '\cap' cap.png
tex2png -lq '\cup' cup.png
tex2png -lq '\partial' partial.png
tex2png -lq '\nabla' nabla.png
tex2png -lq '\infty' infty.png
